### ISSUE TITLE
Injection?

### ISSUE THREAD

**Issue by matthewpersico** [perlancar/perl-App-lcpan#3]
Is there a way to inject locally developed modules (that are not being publicly released) into this local cpan instance?

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

I've coincidentally add an 'inject' subcommand to do exactly this since v1.006 (25 Sep).

Please check it out and tell me if there's a problem with it. lcpan is currently using OrePAN (via its CLI script, orepan.pl) to recreate modules/02packages.details.txt.gz after injection. In my experience, the result might miss some packages. But so far OrePAN is the most hassle-free solution, and I seldom need to inject modules, so I keep using it.

Have you also considered another approach which is to put all your custom modules to a separate CPAN-like repo? Installing modules is equally easy as `cpanm` can accept multiple `--mirror` options (plus the `--mirror-only` option.

**Comment by matthewpersico** [comment]
Actually, no - I have never considered a separate CPAN for local stuff. It never hit me that you can use multiple CPANs. Duh! Thanks for kicking my brain!

**Comment by perlancar** [comment]
This article might be helpful: http://blogs.perl.org/users/steven_haryanto/2014/01/installing-modules-from-cpan-and-your-own-darkpan.html
